robot_base_frame: base_link

obstacle_range: 2.5
raytrace_range: 3.0

footprint:
  [
    [0.45981, 0.32925],
    [0.45981, -0.32925],
    [-0.45981, -0.32925],
    [-0.45981, 0.32925],
  ]
footprint_padding: 0.01
inflation_radius: 0.6

transform_tolerance: 0.5

observation_sources: rslidar_scan rslidar_points #realsense_points #if using realsense point cloud
rslidar_scan:
  {
    data_type: LaserScan,
    topic: /rslidar_laserscan,
    marking: true,
    clearing: true,
  }
rslidar_points:
  {
    data_type: PointCloud2,
    topic: /rslidar_points,
    marking: true,
    clearing: true,
  }
# realsense_points: #if using realsense point cloud
#   {
#     data_type: PointCloud2,
#     topic: /camera/depth/color/points,
#     marking: true,
#     clearing: true,
#   }
