robot_base_frame: base_link

update_frequency: 4.0
publish_frequency: 3.0
obstacle_range: 3.0
raytrace_range: 4.0

footprint:
  [
    [0.45981, 0.32925],
    [0.45981, -0.32925],
    [-0.45981, -0.32925],
    [-0.45981, 0.32925],
  ]
footprint_padding: 0.01
transform_tolerance: 0.5

#layer definitions
static_layer:
  map_topic: map

obstacles_layer:
  track_unknown_space: True
  observation_sources: rslidar_scan
  rslidar_scan:
    {
      data_type: LaserScan,
      topic: laserscan,
      marking: True,
      clearing: True,
      inf_is_valid: True,
    }

voxel_layer:
  track_unknown_space: True
  observation_sources: lidar_points camera_points #if using realsense point cloud
  lidar_points: {
      data_type: PointCloud2,
      topic: rslidar_points,
      marking: True,
      clearing: True,
      inf_is_valid: True,
      min_obstacle_height: 0.12, # meters
      max_obstacle_height: 1.0091, # meters (Robot height : 80.091cm + safety margin: 20cm)
    }
  camera_points: {
      data_type: PointCloud2,
      topic: depth/points,
      marking: True,
      clearing: True,
      min_obstacle_height: 0.12, # meters
      max_obstacle_height: 1.0091, # meters (Robot height : 80.091cm + safety margin: 20cm)
    }

inflation_layer:
  inflation_radius: 0.6
