robot_base_frame: base_footprint

obstacle_range: 3.0
raytrace_range: 4.0

footprint:
  [
    [0.45981, 0.32925],
    [0.45981, -0.32925],
    [-0.45981, -0.32925],
    [-0.45981, 0.32925],
  ]
footprint_padding: 0.01
transform_tolerance: 0.5

#layer definitions
static_layer:
  map_topic: /map

obstacles_layer:
  track_unknown_space: True
  observation_sources: rslidar_scan
  rslidar_scan:
    {
      data_type: LaserScan,
      topic: scan,
      marking: True,
      clearing: True,
    }

voxel_layer:
  min_obstacle_height: 0.0, # meters
  max_obstacle_height: 1.6, # meters (double the robot's height)
  track_unknown_space: True
  observation_sources: lidar_points camera_points #if using realsense point cloud
  lidar_points:
    {
      data_type: PointCloud2,
      topic: rslidar_points,
      marking: True,
      clearing: True
    }
  camera_points:
    {
      data_type: PointCloud2,
      topic: depth/points,
      marking: True,
      clearing: True,
    }

inflation_layer:
  inflation_radius: 1.75
  cost_scaling_factor: 2.58