global_frame: map
rolling_window: False
track_unknown_space: True
static_map: True # use static_map: False if only navigate in odom frame or want to do SLAM

plugins:
  - { name: static_layer, type: "costmap_2d::StaticLayer" }
  - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
