global_frame: map
rolling_window: False
track_unknown_space: True
static_map: True # use static_map: False if only navigate in odom frame or want to do SLAM

publish_frequency: 1.0
update_frequency: 2.0

plugins:
  - { name: static_layer, type: "costmap_2d::StaticLayer" }
  - { name: voxel_layer, type: "costmap_2d::VoxelLayer" }
  - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
