global_frame: odom
rolling_window: True

width: 6.0
height: 6.0
resolution: 0.05

plugins:
  - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: voxel_layer, type: "costmap_2d::VoxelLayer" }
